baseURL = 'https://peterkinget.github.io'
languageCode = 'en-us'
title = 'Peter Kinget Github Homepage'
theme = "cactus"

[[menu.main]]
name = "Home"
url = "/"
weight = 6

[[menu.main]]
name = "Teaching"
url = "http://www.ee.columbia.edu/~kinget/teaching.html" 
weight = 2

[[menu.main]]
name = "Research Group"
url = "http://www.kingetgroup.ee.columbia.edu/"  
weight = 3

[[menu.main]]
name = "Publications"
url = "https://www.ee.columbia.edu/~kinget/publications.html" 
weight = 4

[[menu.main]]
name = "Why Analog"
url = "https://www.ee.columbia.edu/~kinget/why_analog.html"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[params]
 colortheme = "dark"
 mainSection = "about"